### ISSUE TITLE
Apps are broken

### ISSUE THREAD

**Issue by Joschka1** [chrootlogin/docker-nextcloud#10]
Hi, 
since last update Calendar, Contacts and Tasks apps are broken. It's not possible to update and activate them. Doesn't test with oder apps. 
can you pleas fix that? 
best joschka

**Comment by chrootlogin** [comment]
Thats really strange, i didn't have any problems.

Did you remove the docker container before pulling?

**Comment by chrootlogin** [comment]
You could try to remove all files in /data/userapps and install the apps again.

**Comment by Joschka1** [comment]
Hey, forgot to write you, sorry! 
I solved the problem like follow, only remove /data/userapps dosen't solve it: I change cronjob to Ajax, deactivate and uninstalled the first app, reload the page, repeat it for all apps, than reload page again, install the apps again, with also reload page between all installation steps and at last change cronjob bag to default. Thats the only way to works for me. 
Looks like a strange nextcloud bug.

**Comment by chrootlogin** [comment]
That is really strange. I didn't had any issues with the upgrade. But thank you for your report, may it helps someone.

**Comment by mikey0000** [comment]
Yeah I have the same problem. I'll try and find the root cause.

**Comment by mikey0000** [comment]
Due to where I've configured my userapps I had to add
  location ~ /userapps/(.*)$ {                                                                                                                     
      alias /apps2/$1;                                                                                                                               
    }
