### ISSUE TITLE
No sharing in calendars

### ISSUE THREAD

**Issue by plague-doctor** [chrootlogin/docker-nextcloud#13]
I am not sure what is wrong with my setup, but I am missing sharing options in my nextcloud... I have installed and activated calendar and contacts plugins (only those two). I can create new calendars for the user, but there is no way to share them... There is no "share" icon/option for any of them. 
Can you please help to investigate this issue?

**Comment by chrootlogin** [comment]
Did you update the calendars app in the app store? Apart from that you should create an issue here: [github.com/nextcloud/calendar](github.com/nextcloud/calendar), because they are responsible for the calendar app.
