### ISSUE TITLE
New Version 12.0.2

### ISSUE THREAD

**Issue by Joschka1** [chrootlogin/docker-nextcloud#18]
Hi, 
can you pleas update your container to version 12.0.2, because the 12.0.1 is buggy ... 

Thank's and best regards
Joschka

**Comment by chrootlogin** [comment]
Hi @Joschka1 

Thank you for creating the issue. I updated the image to Nextcloud 12.0.2, see https://github.com/chrootLogin/docker-nextcloud/releases/tag/v12.0.2

Have a nice day.
chrootLogin

**Comment by Joschka1** [comment]
Thank you for fast processing!
