### ISSUE TITLE
smb support

### ISSUE THREAD

**Issue by chojuanillo** [chrootlogin/docker-nextcloud#2]
hello!. good job. support for smb?

thanks

**Comment by chrootlogin** [comment]
Hey

I will do it when I've time. But apart from that, if you want to do it yourself you can fork this project and do a pull request.

Cheers

**Comment by JuniorJPDJ** [comment]
Didn't #21 resolve it?

**Comment by chrootlogin** [comment]
The image should support smb since quite a time.
