### ISSUE TITLE
How to configure PHP instance?

### ISSUE THREAD

**Issue by jreimone** [chrootlogin/docker-nextcloud#22]
Hi,
I use this image in a docker-compose context. Today I set the build arg to nextcloud version 12.0.3 and got the following message in the logs:

  server reached pm.max_children setting (5), consider raising it

As I found out, this originates from the PHP included in this image. How can I configure this value?

**Comment by jalcine** [comment]
@jreimone If you haven't found a solution yet; your best bet might be to overwrite the file in a later instance of an image or post-build.

**Comment by chrootlogin** [comment]
You could also create a child image, where you overwrite the setting.

```
FROM rootlogin/nextcloud

COPY my-php-fpm.conf /usr/local/etc/php-fpm.conf
```
This should do the trick.
