### ISSUE TITLE
Nextcloud bump to 13.0.0

### ISSUE THREAD

**Issue by affektde** [chrootlogin/docker-nextcloud#25]
Hola @chrootLogin,
did you plan a bump to 13.0.0? Dunno if there are complications with the new version :-)

All the best from Munich and good work with your Dockerfile!

**Comment by chrootlogin** [comment]
Hi @affektde 

Thank you for informing me about the new version. I will check this evening if there are any problems with bumping the version.

Thanks and have a nice day!
@chrootLogin

**Comment by chrootlogin** [comment]
done!

**Comment by affektde** [comment]
for those who had 500er errrors after update to 13.0.0
After **_nextcloud upgrade command_** under cli, everything works like a charm.

``docker exec -it CONTAINERNAME occ upgrade``
