### ISSUE TITLE
alpine linux has no usermod | important for file access

### ISSUE THREAD

**Issue by affektde** [chrootlogin/docker-nextcloud#3]
Hello @chrootLogin ,
thanks for your work with this image. I like it.

Can you give a hint or a possibility to change a user id for file access issues.
In all my docker containers I change the userid of www-data, because all containers will work with www-data.

Like this:

```
ARG USERID=501
RUN usermod -u $USERID -o www-data
```

But alpine linux has no usermod, so I have to do fancy /etc/passwd stuff. Maybe you have a better solution for it.

There are solution with alpine linux, where developers delete a user and add it with another id. Like this:

```
echo "change user / group"
 +    deluser ${USER}
 +    addgroup -g ${NAMED_GID} ${GROUP}
 +    adduser -u ${NAMED_UID} -G ${GROUP} -g 'Linux User named' -s /sbin/nologin -D ${USER}
 +    echo "[DONE]"
 +    echo "Set owner and permissions for old uid/gid files"
 +    find / -user ${NAMED_UID_ACTUAL} -exec chown ${USER} {} \;
 +    find / -group ${NAMED_GID_ACTUAL} -exec chgrp ${GROUP} {} \;
 +    echo "[DONE]"
```

[https://github.com/pstauffer/docker-bind/pull/11/files](url)

Your are running php-fpm as nobody, so for me it is not clear, what to do now.

At the end I only want to have the php-process running with another userid.

**Comment by chrootlogin** [comment]
I will look into this in the next few days, but it shouldn't be a big deal to fix this.

**Comment by chrootlogin** [comment]
You can now use build arguments. Use as example `docker -t rootlogin/nextcloud --build-arg UID=1000 --build-arg GID=1000 . && docker run -p 80:80 docker/nextcloud`. This should solve your problem.

**Comment by affektde** [comment]
This is very helpful and solves my problem with mounted volumes and their write permissions. Thank you very much for this! Will inform you about success in a short.

**Comment by affektde** [comment]
![image](https://cloud.githubusercontent.com/assets/5022192/19067649/753cd99c-8a1f-11e6-8d43-412bb3b84aac.png)

Thanks! Works like a charm! All files are now created with the right user id!!! Thumbs up!

**Comment by meetmatt** [comment]
@chrootLogin what if you need to do it in runtime, e.g. running a container by users with different UID's?

**Comment by sonu27** [comment]
You can install it using:
```
RUN echo http://dl-2.alpinelinux.org/alpine/edge/community/ >> /etc/apk/repositories
RUN apk --no-cache add shadow && usermod -u 1000 www-data
```

**Comment by chrootlogin** [comment]
@meetmatt What you want to achieve? 
On every restart the container resets all user/group IDs according to the UID/GID setting on build.

**Comment by matteo-gz** [comment]
> You can install it using:
> 
> ```
> RUN echo http://dl-2.alpinelinux.org/alpine/edge/community/ >> /etc/apk/repositories
> RUN apk --no-cache add shadow && usermod -u 1000 www-data
> ```
thank your tip
