### ISSUE TITLE
Create tags 13.0.6 and 13-latest

### ISSUE THREAD

**Issue by AlterDepp** [chrootlogin/docker-nextcloud#31]
Can you please create the metioned tags on docker.

Thanks Stefan

**Comment by chrootlogin** [comment]
Tag 13.0.6 already exists: https://github.com/chrootlogin/docker-nextcloud/tree/13.0.6
And I don't plan to create 13-latest, as 14.0.0 already exists. May I could create 14-latest

**Comment by AlterDepp** [comment]
Sorry, I meant the tag on docker.com.

**Comment by chrootlogin** [comment]
Somehow docker stopped building my tags -.- Started the build... -> https://hub.docker.com/r/rootlogin/nextcloud/builds/

**Comment by AlterDepp** [comment]
Thanks
