### ISSUE TITLE
Proxy IP in nginx logs

### ISSUE THREAD

**Issue by JuniorJPDJ** [chrootlogin/docker-nextcloud#39]
There's how to fix it:
https://stackoverflow.com/questions/36268272/nginx-allowing-origin-ip#36270273

Can you provide a way to set this var by env or something?

**Comment by chrootlogin** [comment]
I think that should now be fixed: https://github.com/chrootlogin/docker-nextcloud/blob/da8b8d45759abe79eb4da9192ec0bdf61a0dd9a5/root/etc/nginx/nginx.conf
