### ISSUE TITLE
Update icon code

### ISSUE THREAD

**Issue by wj844908240** [chrootlogin/docker-nextcloud#43]
I want to change the code that displays different icons according to the uploaded file.
Changed the mimeTypeIcon method of  /opt/nextcloud/lib/private/Files/Type/Detection.php , but it didn't work.
Even deleted directory  /opt/nextcloud/core/img/filetypes  , but the page did not change at all.
I changed and exited the container and restarted it without effect.
Is there a cache?
Thank you for helping.

**Comment by chrootlogin** [comment]
This is by design of docker. The directory /opt/nextcloud isn't a volume, so it always resets to its defaults on restart.
