### ISSUE TITLE
Support for custom 'session.save_handler'

### ISSUE THREAD

**Issue by rossigee** [chrootlogin/docker-nextcloud#46]
Would be really useful to be able to set the `session.save_handler` and `session.save_path`, for example by passing `SESSION_SAVE_HANDLER` and `SESSION_SAVE_PATH` envvars to the container.

This would make it fairly trivial to scale the container out in a cluster without having to customise/extend the base image.

**Comment by chrootlogin** [comment]
This image has been moved to [erhardtconsulting/nextcloud](https://github.com/erhardtconsulting/images/tree/main/nextcloud) and is now rootless and compatible with Kubernetes.
