### ISSUE TITLE
Update to Nextcloud 18.X

### ISSUE THREAD

**Issue by onny** [chrootlogin/docker-nextcloud#49]
Hey,
please update the version to Nextcloud 18.

Best regards
Jonas

**Comment by onny** [comment]
Releated pull request: https://github.com/chrootlogin/docker-nextcloud/pull/48

**Comment by ccellist** [comment]
I was looking at the readme and the PR is only to update the default for the arg in the dockerfile. All you have to do to get the latest version is specify --build-arg NEXTCLOUD_VERSION=18.0.3 at build time and you'll get the version you need. I'm not even sure you need to supply a new value for GPG. As such you don't really need the PR. Just run the correct build command and you're all set.

**Comment by chrootlogin** [comment]
This is obsolet. We now have 19.0.2
