### ISSUE TITLE
Add support of ARM architecture

### ISSUE THREAD

**Issue by sadmin91** [chrootlogin/docker-nextcloud#50]
I'm using your container definition on my raspberry Pi.
To doing this, I have change the base image of your Dockerfile from `php:7.3-fpm-alpine` to `arm32v6/php:7.3-fpm-alpine`.

Do you think is possible to add this modification on this repo ?

**Comment by ccellist** [comment]
I'm not a maintainer to this, just a contributor and this ticket is reasonably old, but it seems to me you should be able to fork this, make and test the necessary modifications, then submit a PR. Not sure how @chrootlogin wants to handle multiple platforms of this image.

**Comment by chrootlogin** [comment]
Hi @sadmin91

Thanks for your suggestion! I added multi-arch images through Github Actions. Now the image is built for x86, amd64, armv6, armv7, arm64, ppc64le and s390x. 

You can now also use fixed architecture tags like **rootlogin/nextcloud:develop-armv6**. The normal tags like **rootlogin/nextcloud:develop** or version tags like **rootlogin/nextcloud:20.0.0** will provide the correct image according your architecture.

I hope this helps!
