### ISSUE TITLE
Suppor for prereleases

### ISSUE THREAD

**Issue by onny** [chrootlogin/docker-nextcloud#56]
Hey,
thanks for your nice Nextcloud container. It is really simple and works very well :)

I wanted to test out Nextcloud 21 RC1 prerelease to check out compatibility with my apps. I guess setting NEXTCLOUD_VERSION=21.0.0.RC1 as build argument wont work because the hardcoded wget command uses the url "/releases/" and not "/prereleases" ( https://download.nextcloud.com/server/prereleases/ ).
So maybe try to download from /releases and if that doesn't work try to download from /prereleases. Only fail if second try errors.

Best regards
Jonas

**Comment by chrootlogin** [comment]
This image has been moved to [erhardtconsulting/nextcloud](https://github.com/erhardtconsulting/images/tree/main/nextcloud) and is now rootless and compatible with Kubernetes.
