### ISSUE TITLE
Read php error log

### ISSUE THREAD

**Issue by onny** [chrootlogin/docker-nextcloud#57]
Hey,
what is the best way to read the php error log?
Currently I'm restarting the process php-fpm in a bash shell to see whats going on. Is it possible to read the php error logs from outside the cointainer?
Best regards
Jonas

**Comment by chrootlogin** [comment]
Hey!

I think PHP errors should be printed out directly to stdout and stderr, so they should be able to get by `docker logs [container-name]`. Does that not work?

Best regards
Simon

**Comment by onny** [comment]
Oh thank you that was easy :)
