### ISSUE TITLE
last version of apcu require extra config

### ISSUE THREAD

**Issue by vbauchart** [chrootlogin/docker-nextcloud#58]
just rebuilt my docker image and I get this error:

```
# docker-compose exec nextcloud occ upgrade
An unhandled exception has been thrown:
OC\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)
```

I dont get time to find out why I get this error but it seems related to https://github.com/nextcloud/vm/issues/2039

So I just add this parameter

`echo "apc.enable_cli=1" >> /usr/local/etc/php/conf.d/apcu.ini` into my running image to achieve the upgrade.

This bug should be analyse carefuly but I hope this trick will help other people having  the same issue

**Comment by chrootlogin** [comment]
This image has been moved to [erhardtconsulting/nextcloud](https://github.com/erhardtconsulting/images/tree/main/nextcloud) and is now rootless and compatible with Kubernetes.
