### ISSUE TITLE
Nextcloud Version 11.0.1

### ISSUE THREAD

**Issue by Joschka1** [chrootlogin/docker-nextcloud#8]
Pleas can you add the version 11.0.1, this version will fixe some bugs and security updates.
Thank you! 
Joschka

**Comment by chrootlogin** [comment]
Hello Joschka1

Thank you for your notice. I updated the Dockerfile and made a new release.

Cheers Simon

**Comment by Joschka1** [comment]
Thank you for fast processing! 
Cheers Joschka
